version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # NOTE: We must expose these args to Dockerfile because they are used in next.config.js
      args:
        - CHAIN_ID=${CHAIN_ID}
        - BLOCKCHAIN_EXPLORER_URL=${BLOCKCHAIN_EXPLORER_URL}
        - MARKETPLACE_CONTRACT=${MARKETPLACE_CONTRACT}
        - TOKEN_CONTRACT=${TOKEN_CONTRACT}
    env_file: .env
    stdin_open: true
    tty: true
    ports:
      - 127.0.0.1:3000:3000
      # NOTE: In case, if you want to use ./ops/nginx.sh, uncomment this line:
      # - 3000:3000
